- name: Adding new user
  hosts: all
  become: true
  
  tasks:

  - name: Create user with a home directory
    user:
      name: "{{ ansible_user }}"
      shell: /bin/bash
      create_home: yes
      password: "{{ user_password }}"

  - name: Allow authenticate with password
    loop:
      - /etc/ssh/sshd_config
      - /etc/ssh/sshd_config.d/50-cloudimg-settings.conf
      - /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
    lineinfile:
      path: "{{ item }}"
      regexp: '^#?PasswordAuthentication\s'
      line: "PasswordAuthentication yes"
      state: present
      validate: '/usr/sbin/sshd -t -f %s'

  - name: Restart SSH
    systemd_service:
      name: ssh
      state: restarted
      daemon_reload: true
