- name: Building Dumbmerch Backend app in build server
  hosts: build_server

  tasks:

    - name: Pull latest code
      git:
        repo: "git@github.com:millinov/be-dumbmerch.git"
        dest: "{{ ansible_user_dir }}/project/be-dumbmerch"
        version: staging
        update: true

    - name: Build and push image
      community.docker.docker_image:
        name: "registry.millinov.studentdumbways.my.id/backend-dumbmerch:v1"
        source: build
        force_source: true
        build:
          path: "{{ ansible_user_dir }}/project/be-dumbmerch"
          nocache: true
        push: true


