- name: Deploying Jenkins
  hosts: jenkins

  vars:
    build_server_host: 10.184.0.2

  tasks:

    - name: Check If Docker Is Installed
      command: docker --version
      register: docker_valid
      changed_when: false
      failed_when: false

    - name: Debug Docker Output
      debug:
        var: docker_valid 

    - name: If no docker, run install docker
      when: docker_valid.rc != 0
      include_tasks:
        file: "{{ ansible_directory }}/tasks/install-docker.yaml"
        apply:
          become: true 

    - name: If yes docker are running
      when: not docker_valid.failed
      block:
        - name: Ensure docker directory exists
          file:
            path: "{{ ansible_user_dir }}/docker"
            state: directory
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0755'

        - name: Copying docker-compose
          copy:
            src: jenkins-compose.yaml
            dest: "{{ ansible_user_dir }}/docker/docker-compose.yaml"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            mode: '0755'

        - name: Check Docker Compose status
          command:
            cmd: docker compose ps --status running -q
            chdir: "{{ ansible_user_dir }}/docker"
          register: compose_check
          changed_when: false
          failed_when: false

        - name: Debug compose_check Output
          debug:
            var: compose_check 

        - name: Turn off docker compose first
          when: compose_check.stdout != ""
          command: 
            cmd: docker compose down
            chdir: "{{ ansible_user_dir }}/docker"
        
        - name: Run docker compose
          command: 
            cmd: docker compose up -d
            chdir: "{{ ansible_user_dir }}/docker"

        - name: Create Jenkins SSH directory
          shell:
            cmd: docker exec jenkins mkdir -p /var/jenkins_home/.ssh

        - name: Get build VM SSH host key
          command:
            cmd: "ssh-keyscan -p 3333 {{ build_server_host }}"
          register: build_vm_hostkey
          changed_when: false

        - name: Add build VM host key
          become: true
          shell:  |
            docker exec jenkins bash -c \
            'printf "%s\n" "{{ build_vm_hostkey.stdout }}" >> /var/jenkins_home/.ssh/known_hosts'
            
        - name: Get initial admin password
          command: 
            cmd: docker compose exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
            chdir: "{{ ansible_user_dir }}/docker"
          register: jenkins_admin_pass
          changed_when: false
          failed_when: false

        # Kalau jenkins sudah di inisialisasi mungkin filenya tidak ada
        - name: Debug jenkins_admin_pass Output
          debug:
            var: jenkins_admin_pass 