- name: Deploy K3S - Lightweight Kubernetes on Kube Worker Node
  hosts: kube_worker
  become: true 

  tasks:

    - name: Check If K3S Is Installed
      command: systemctl is-active k3s-agent
      register: k3s_agent_status
      changed_when: false
      failed_when: false

    - name: Debug K3S Output
      debug:
        var: k3s_agent_status 
        
    - name: If error, install K3S
      when: k3s_agent_status.rc != 0
      block:
        - name: Set worker hostname
          hostname:
            name: "worker{{ groups['kube_worker'].index(inventory_hostname) + 1 }}"

        - name: Write hostname file
          copy:
            content: "worker{{ groups['kube_worker'].index(inventory_hostname) + 1 }}\n"
            dest: /etc/hostname

        - name: Install K3S
          shell:  |
            curl -sfL https://get.k3s.io | \
            K3S_URL=https://10.184.0.12:6443 \
            K3S_TOKEN="{{ master_token }}" \
            sh -

    - name: Setup Kube agent Config
      copy:
        dest: /etc/rancher/node/config.yaml
        owner: root
        group: root
        mode: '0644'
        content: |
          disable: servicelb
          disable: traefik
          default-local-storage-path: /mnt/disk1