apiVersion: v1
kind: Secret
metadata:
  name: backend-env
  namespace: dumbmerch
type: Opaque
stringData:
  SECRET_KEY: bolehapaaja
  PATH_FILE: http://localhost:5000/uploads/
  SERVER_KEY: Key
  CLIENT_KEY: Key
  EMAIL_SYSTEM: demo.dumbways@gmail.com
  PASSWORD_SYSTEM: Password
  DB_HOST: postgres-service
  DB_USER: finaltask-miral
  DB_PASSWORD: miral1906
  DB_NAME: dumbmerch
  DB_PORT: "5432" 
  PORT: "5000"