apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: token

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dumbmerch
type: Opaque
stringData:
  POSTGRES_USER: finaltask-miral
  POSTGRES_PASSWORD: "miral1906"
  POSTGRES_DB: dumbmerch