upstream backend {
    server 10.184.0.3:5000;
    server 10.184.0.9:5000;
}

server {
    listen 80;
    server_name api.staging.millinov.studentdumbways.my.id;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/staging.millinov.studentdumbways.my.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/staging.millinov.studentdumbways.my.id/privkey.pem;

    server_name api.staging.millinov.studentdumbways.my.id;

    client_max_body_size 0;

    location / {
        proxy_pass         http://backend;

        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}